spring.application.name=AnimalWelFare
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.datasource.url=jdbc:mysql://localhost:3306/animalwelfaredb
# Aapne root password set kiya tha
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
# 'update' se Hibernate automatically tables create/update kar dega
spring.jpa.hibernate.ddl-auto=update
# SQL queries console par dekhne ke liye
spring.jpa.show-sql=true
# MySQL 8 Dialect (Spring Boot 3/MySQL 8 ke liye optimized)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unitedforanimalwelfare@gmail.com
spring.mail.password=tpuk yitj tprj aeyn
#Jaibabaki1990@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Test Mode Configuration
easebuzz.env=test
easebuzz.key=1ZSOIWQXZ
easebuzz.salt=TANCKA15Z
easebuzz.url=https://testpay.easebuzz.in/payment/initiate_link
easebuzz.initiate.url = https://testpay.easebuzz.in/payment/initiateLink
easebuzz.initiate.accesskeyUrl = https://testpay.easebuzz.in/pay/
easebuzz.redirect.domain.url= https://sheath-duplicate-parchment.ngrok-free.dev
easebuzz.application.domain.url = http://localhost:5173

meta.whatsapp.phone-id=1151236754732758
meta.whatsapp.token=EAAXrRmsiWGUBRVJgFVoRZBgqGvRJvWZAublOdLexG2ZCB05yvz3Ur2TAv9St1opMlaZBJim7GeAFkVtWKZBaZCnTWQuNbB5K05H2xKfgiSW6uZA6P6tJoh3Wd1RuzEbmQlkS7Mcy0SpGjuzsygX3dvDG9seeV9S0i6rmpRzUxUUan5FEMEZCFZAOQEauxjaGkqIZCbSdkfJqa6GlhlpZAydrzYazfYBsD2a8Yx6gr5ZChm38Ys30xTkE3hCgCV3WCnXiH0IaCsncerDRTeDBQB58VpnXuhVV
meta.whatsapp.url =https://graph.facebook.com/v21.0/

cloudinary.cloud-name=dfqg5opfb
cloudinary.api-key=888744762836411
cloudinary.api-secret=NzNgRawrHjPyVRGzSq8-LdYlJRg

app.jwt.secret=${JWT_SECRET:z8Xp2W9vR5mNq4L7k6J3hG1fD0sA9bC8vE7xR6tY5uI4oO3pP2qA1sS2dD3fF4gG}
# Production ke time bas ye change karna hoga
# easebuzz.url=https://pay.easebuzz.in/payment/initiate_link

# Optional: explicitly enable the jdbc health indicator (auto-enabled when DataSource and JDBC driver on classpath)
# management.health.db.enabled=true